- name: Setup development environment
  hosts: dev
  tasks:
    - name: Remove `Connect Your Online Accounts` popup
      become: true
      apt:
        name: gnome-initial-setup
        state: absent
      register: remove_gnome_initial_setup
    - name: Killall `Connect Your Online Accounts` popup
      become: true
      shell: killall gnome-initial-setup
      ignore_errors: true  # In case the process is not running
      when: remove_gnome_initial_setup.changed
    - name: Install common tools
      become: true
      apt:
        name:
          - curl
          - git
          - htop
          - iputils-ping
          - nano
          - net-tools
          - tmux
          - tree
          - unzip
          - vim
          - wget
          - zip
        state: present
        update_cache: yes
    - name: Upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      become: true
      reboot:
      when: reboot_required_file.stat.exists == true
