# Ref: https://docs.docker.com/engine/install/ubuntu/
# Potential Future Ref: https://github.com/geerlingguy/ansible-role-docker
- name: Uninstall old versions of Docker conflicting packages
  become: true
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: true

- name: Install required packages
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    update_cache: true

- name: Create directory for Docker GPG key
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb [arch={{ arch_map[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: true

- name: Install Docker packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Ensure docker group exists
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
