- name: Enable automatic login
  become: true
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#.*AutomaticLoginEnable.*=.*$'
    line: 'AutomaticLoginEnable = true'
  register: enable_auto_login
- name: Set automatic login user
  become: true
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#.*AutomaticLogin.*=.*$'
    line: 'AutomaticLogin = {{ ansible_user_id }}'

- name: Disable Screen Lock
  dconf:
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: false
