- name: Enable automatic login
  become: true
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#.*AutomaticLoginEnable.*=.*$'
    line: 'AutomaticLoginEnable = true'
  register: enable_auto_login
- name: Set automatic login user
  become: true
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#.*AutomaticLogin.*=.*$'
    line: 'AutomaticLogin = {{ ansible_user_id }}'
- name: Require reboot
  copy:
    content: ""
    dest: /var/run/reboot-required
    force: false
    owner: root
    group: root
    mode: '0644'
  when: enable_auto_login.changed

- name: Disable Screen Lock
  dconf:
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: false
