- name: Install psutil for `dconf`
  pip:
    name: psutil
    state: present
- name: Set GNOME favorite apps
  dconf:
    key: /org/gnome/shell/favorite-apps
    value: "['firefox_firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.gedit.desktop']"
    state: present
