- name: Install GUI debugging tools
  # - `x11-apps` and `x11-utils` for `xeyes` and `xdpyinfo`
  #   Ref: https://packages.debian.org/sid/x11-apps
  #   Ref: https://packages.debian.org/sid/x11-utils
  # - `mesa-utils` for `glxgears` and `glxinfo`
  #   Ref: https://wiki.debian.org/Mesa
  # - `vulkan-tools` for `vkcube` and `vulkaninfo`
  #   Ref: https://docs.vulkan.org/tutorial/latest/02_Development_environment.html#_vulkan_packages
  #   Ref: https://gitlab.com/nvidia/container-images/vulkan/-/blob/master/docker/Dockerfile.ubuntu
  become: true
  apt:
    name:
      - x11-apps
      - x11-utils
      - mesa-utils
      - libgl1
      - vulkan-tools
    update_cache: true
