# Ref: https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating
- name: Check if nvm is installed
  stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.nvm/nvm.sh"
  register: nvm_check

- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.nvm/nvm.sh"
  when: not nvm_check.stat.exists

- name: Check whether Node.js install via nvm is needed
  shell: |
    source {{ ansible_facts['env']['HOME'] }}/.nvm/nvm.sh
    installed_version="$(nvm version node)"
    remote_version="$(nvm version-remote node)"
    if [ "$installed_version" = "N/A" ] || [ "$installed_version" != "$remote_version" ]; then
      echo install_needed=true
    else
      echo install_needed=false
    fi
  args:
    executable: /bin/bash
  register: nvm_node_status
  changed_when: false

- name: Install Node.js using nvm
  shell: |
    source {{ ansible_facts['env']['HOME'] }}/.nvm/nvm.sh
    nvm install node
  args:
    executable: /bin/bash
  when: "'install_needed=true' in nvm_node_status.stdout"
