# References:
# - https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
# - https://github.com/NVIDIA/ansible-role-nvidia-docker

# Although this could be simplified by directly storing as `.asc` file,
# I prefer to keep the `.gpg` extension to faithfully reflect the
# official instructions so as to prevent potential future issues.
- name: Check if (dearmored) GPG key exists
  stat:
    path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  register: nvidia_container_toolkit_keyring_gpg
- name: Download GPG key if not dearmored
  get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /tmp/nvidia-container-toolkit-keyring.gpg
    mode: '0644'
  when: not nvidia_container_toolkit_keyring_gpg.stat.exists
- name: Dearmor the GPG key if not already done
  become: true
  shell: |
    gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia-container-toolkit-keyring.gpg
  when: not nvidia_container_toolkit_keyring_gpg.stat.exists

- name: Check if repository list exists
  stat:
    path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  register: nvidia_container_toolkit_list
- name: Download repository list
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /tmp/nvidia-container-toolkit.list
  when: not nvidia_container_toolkit_list.stat.exists
- name: Modify the repository list
  replace:
    path: /tmp/nvidia-container-toolkit.list
    regexp: 'deb https://'
    replace: 'deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://'
  when: not nvidia_container_toolkit_list.stat.exists
- name: Write the modified repository list to sources.list.d
  become: true
  copy:
    remote_src: true
    src: /tmp/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    owner: root
    group: root
    mode: '0644'
  when: not nvidia_container_toolkit_list.stat.exists

- name: Install nvidia-container-toolkit
  become: true
  apt:
    name: nvidia-container-toolkit
    state: present
    update_cache: true
  register: install_nvidia_docker

- name: Check if Docker daemon configuration exists
  stat:
    path: /etc/docker/daemon.json
  register: docker_daemon_json
- name: Run nvidia container toolkit
  become: true
  command: nvidia-ctk runtime configure --runtime=docker
  when: not docker_daemon_json.stat.exists

- name: Restart docker
  become: true
  systemd:
    name: docker
    daemon_reload: true
    state: restarted
  when: install_nvidia_docker.changed
