- name: Remove `Connect Your Online Accounts` popup
  become: true
  apt:
    name: gnome-initial-setup
    state: absent
  register: remove_gnome_initial_setup
- name: Killall `Connect Your Online Accounts` popup
  shell: killall gnome-initial-setup
  ignore_errors: true  # In case the process is not running
  when: remove_gnome_initial_setup.changed

- name: Remove `Upgrade Available` popup
  become: true
  apt:
    name: ubuntu-release-upgrader-core
    state: absent
  register: remove_ubuntu_release_upgrader_core
- name: Killall `Upgrade Available` popup
  shell: killall check-new-release-gtk
  ignore_errors: true  # In case the process is not running
  when: remove_ubuntu_release_upgrader_core.changed
