- name: Set Ubuntu Desktop scale to 100%
  # Notes:
  # - /org/gnome/desktop/interface/scaling-factor defaults to uint32 0 (automatic)
  # - Forcing uint32 1 corresponds to 100% integer scaling
  # - Equivalent to `gsettings set org.gnome.desktop.interface scaling-factor 1`
  dconf:
    key: /org/gnome/desktop/interface/scaling-factor
    value: "uint32 1"
- name: Require reboot
  become: true
  copy:
    content: ""
    dest: /var/run/reboot-required
    force: false
    owner: root
    group: root
    mode: '0644'
  when: enable_auto_login.changed
