# Known issues:
# - Vino VNC will have issues when the Display Scaling is not 100%.
#   Ref: https://bugs.launchpad.net/ubuntu/+source/vino/+bug/1668309
#   Ref: https://gitlab.gnome.org/Archive/vino/-/issues/9
# - In addition, Vino VNC is archived and not actively maintained.
#   Ref: https://gitlab.gnome.org/Archive/vino
- name: Install Vino VNC
  become: true
  apt:
    name: vino
    update_cache: true
- name: Disable prompt
  dconf:
    key: /org/gnome/desktop/remote-access/prompt-enabled
    value: false
- name: Disable encryption
  dconf:
    key: /org/gnome/desktop/remote-access/require-encryption
    value: false
- name: Only allow local connections (must use SSH tunneling)
  # Ref: https://help.ubuntu.com/community/VNC/Servers#vino
  dconf:
    key: /org/gnome/desktop/remote-access/network-interface
    value: "'lo'"
- name: Create autostart directory
  file:
    path: ~/.config/autostart
    state: directory
    mode: '0755'
- name: Create vino-server.desktop for autostart
  copy:
    dest: ~/.config/autostart/vino-server.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Name=Vino VNC server
      Exec=/usr/lib/vino/vino-server
      NoDisplay=true
    mode: '0644'
  register: vino_server_desktop_autostart
- name: Require reboot
  become: true
  copy:
    content: ""
    dest: /var/run/reboot-required
    force: false
    owner: root
    group: root
    mode: '0644'
  when: vino_server_desktop_autostart.changed
- name: Allow VNC access from internal network
  become: true
  ufw:
    rule: allow
    src: 192.168.0.0/16
    port: 5900
    proto: tcp
